apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
  labels:
    app: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris
  strategy:
    type: RollingUpdate   # Upgrade this application with a rolling strategy
    rollingUpdate:
      maxSurge: 1         # maximum number of pods that can be scheduled
                          # above the desired number of pods (replicas)
      maxUnavailable: 0   # the maximum number of pods that can be unavailable
                          # during the update
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - image: helm-valip-quay-quay-quay.apps.vapo-aws-dsoi-dev.va.gov/helm/irishealth/irishealth:2022.1.0.209.0
        name: iris
        ports:
        - name: superserver
          containerPort: 1972
          protocol: TCP
        - name: webserver
          containerPort: 52773
          protocol: TCP
      imagePullSecrets:
      - name: vapo-quay-helm-valip-robot-chcgchdctc
