apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
  labels:
    app: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris
  strategy:
    type: RollingUpdate   # Upgrade this application with a rolling strategy
    rollingUpdate:
      maxSurge: 1         # maximum number of pods that can be scheduled
                          # above the desired number of pods (replicas)
      maxUnavailable: 0   # the maximum number of pods that can be unavailable
                          # during the update
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - image: quay.vapo.va.gov/scm/irishealth/iris-scm-msgbank:2021.2.0.651.0
        name: iris
        ports:
        - name: superserver
          containerPort: 1972
          protocol: TCP
        - name: webserver
          containerPort: 52773
          protocol: TCP
        volumeMounts:
        - mountPath: "/irissys/data/"
          name: my-pv-storage
      imagePullSecrets:
      - name: vapo-quay-helm-valip-robot-chcgchdctc
      volumes:
      - name: my-pv-storage
        persistentVolumeClaim:
          claimName: iris-data-helm-valip-dev-iris-msgbank-data-0-0-clone
---
apiVersion: v1
kind: Service             # oc expose service/test-clusterip
metadata:
  name: test-clusterip
spec:
  type: ClusterIP
  selector:
    app: iris
  ports:
    - port: 52773
      targetPort: 52773
